### ISSUE TITLE
Add LICENCE

### ISSUE THREAD

**Issue by urosgruber** [blabber/go-freebsd-sysctl#2]
Would you be able to add a LICENCE file sincer this lib is used in Datadog integration.

**Comment by blabber** [comment]
Sure. It is nice to see, that this stuff is useful to you. I mainly wrote this code to learn how to use the "C" pseudo package.

**Comment by urosgruber** [comment]
Hey @blabber Thanks for quick response. I'm affraid the change is not ideal. Could you please check why exactly here https://github.com/DataDog/datadog-agent/pull/6787#discussion_r529680564
Would it be possible to make this change. I think a lot of FreeBSD users would appreciate about this. Also thank you for this piece of code you created.

**Comment by blabber** [comment]
I see. I would be willing to relicense this stuff as [0BSD](https://opensource.org/licenses/0BSD) licensed, if @NHOrus, as the only contributor besides me, is okay with it.

**Comment by urosgruber** [comment]
Ok, thanks. Let's wait until @NHOrus respond.

**Comment by NHOrus** [comment]
I m ok with this
